### ISSUE TITLE
Test the NuGet support with Chocolatey

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1113]
# Task Description

We need feedback on how well our NuGet layout provider works with Chocolatey.

You might find the [`strongbox-examples`](https://github.com/strongbox/strongbox-examples/) useful. Perhaps creating a similar example using Chocolatey would be helpful.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by BGhass** [comment]
I will take a look at this.

**Comment by carlspring** [comment]
Hi!

Feel free to do so! :)

**Comment by BGhass** [comment]
thanks, It's my first participation in StrongBox. So, I think that I will need some help. :)

**Comment by carlspring** [comment]
@BGhass : Okay, no problem! Have you used NuGet / Chocolatey before?

**Comment by BGhass** [comment]
NuGet yes I did, Chocolatey No?

**Comment by carlspring** [comment]
Okay, good luck and please report back any issues! :)

**Comment by TheCakeIsNaOH** [comment]
Chocolatey has issues installing, searching, and upgrading packages that have a hyphen/dash in their name from Strongbox. Many, quite possibly a majority of packages on Chocolatey.org have a hyphen in their name as it is the recommended way to deal with a space in the name of the software rather than say a dot.

Install requests from nuget.exe are similar to this, and work fine-
`0.0.0.0:48080/storages/public/nuget-group/FindPackagesById()?id='testing-2'&semVerLevel=2.0.0`
While install requests from chocolatey are formated like this-
`0.0.0.0:48080/storages/public/nuget-group/Packages()?$filter=(tolower(Id)%20eq%20'testing-2')%20and%20IsLatestVersion`
Both are trying to install a packaged named `testing-2` which is on the server, nuget.exe seccessfully installs it, but chocolatey fails. Chocolatey works fine installing from strongbox with packages names that do not have a hyphen, such as `testing`.

I think the AQL included in Strongbox is not accepting the HTTP requests from Chocolatey as valid formating. If I try the chocolatey request in a web browser, it replies as such-
`{"error":"AQL syntax error at [1:24], cause [token recognition error at: '-']\nAQL syntax error at [1:25], cause [extraneous input '2' expecting ''']"}`

**Comment by carlspring** [comment]
You might want to have a look at these classes:
* [`NugetODataFilter`](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/antlr4/org/carlspring/strongbox/nuget/filter/NugetODataFilter.g4)
* [`org/carlspring/strongbox/nuget/filter`](https://github.com/strongbox/strongbox/tree/master/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/src/main/java/org/carlspring/strongbox/nuget/filter).

It seems the grammar file needs some tweaking.

@sbespalov : Any suggestions?

@TheCakeIsNaOH : Thank you for your efforts in investigating this! Could you please provide a simple test case in Java, so that we could look into it?

**Comment by TheCakeIsNaOH** [comment]
> Could you please provide a simple test case in Java, so that we could look into it?
Like as a separate application or as a code test in strongbox?

**Comment by carlspring** [comment]
I would say more like a proper JUnit test case that tries the above. Have a look at the Nuget controller test, or the ones in the Nuget layout provider for more details.

**Comment by carlspring** [comment]
@TheCakeIsNaOH , @anki2189 , @gretel, @steve-todorov ,

Are we okay to now close this?

**Comment by steve-todorov** [comment]
Yes, we have tests for it now and it's included in the main pipeline.
