### ISSUE TITLE
Rename the org.carlspring.strongbox.storage.metadata.nuget.metadata as to not repeat itself

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1121]
There seems to now be a packaged called `org.carlspring.strongbox.storage.metadata.nuget.metadata`. This is a bit too repetitive. It should just be `org.carlspring.strongbox.storage.metadata.nuget`.

This task is a continuation of #611 and #1106.

**Comment by kalski** [comment]
@carlspring there is a notion in nuget's nuspec called metadata - https://docs.microsoft.com/en-us/nuget/reference/nuspec#general-form-and-schema

That's why I kept the classes representing it under `org.carlspring.strongbox.storage.metadata.nuget.metadata`.  

It's not the best package name I could think of but I thought it's better to have it than to put those 18 classes in the same namespace.

BTW I noticed `strongbox-storage-nuget-layout-provider/src/test/java` still has the `org.carlspring.strongbox.storage.metadata.nuget.metadata` namespace.
