### ISSUE TITLE
Merge (if possible) ObjectMapper implementations: StrongboxYamlMapper and CustomObjectMapper

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1166]
# Task Description

Soon, we will be using two implementations of `com.fasterxml.jackson.databind.ObjectMapper`:

- `org.carlspring.strongbox.mapper.CustomObjectMapper` for JSON
- `org.carlspring.strongbox.yaml.StrongboxYamlMapper` for YAML

We should try to merge these implementations and use only one. Once it's done, we should try to use single instance of `MappingJackson2HttpMessageConverter` for both JSON and YAML (see `org.carlspring.strongbox.config.WebConfig`).

# Task Relationships

This task depends on #965 (#1056).

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by sbespalov** [comment]
I think we don't need to do this. These Mappers is not the same because it used for different purposes. Also changes on Configuration serialization shouldn't affect on Web serialization. If there is something common there and you want to improve it then we should extract just this common parts and use them for both Mappers.

**Comment by fuss86** [comment]
We're using `StrongboxYamlMapper` for Web serialization too (there is a possibility to download the yaml configuration). At least we should try to use some base class for them.

**Comment by carlspring** [comment]
@fuss86 / @sbespalov ,

What's the status of this task? Is this something we need to further discuss? Is there a value in it? Should we close it?

**Comment by carlspring** [comment]
@sbespalov . @steve-todorov ,

Any further thoughts on this? Should we add it to #hacktoberfest / #ghc2020 , or should we close it?

**Comment by steve-todorov** [comment]
To be honest, I think we should actually `remove` the ability to `GET` the configuration. This could leak some passwords in the future. It does make sense to have an option to `PUT`, but this would still be a security issue - there would need to be a `root` admin and only he should be able replace the `strongbox.yaml` config. In the long run it might be worth researching ways of incorporating `etcd` or `consul` for storing the configuration since it's distributed and can also be used for discovery.

**Comment by carlspring** [comment]
Okay, I'll close this issue for now.
