### ISSUE TITLE
Implement a PypiWheelDependencyFormatter

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1176]
# Task Description

We will need to be able to generate dependency snippets that a user would be able to cut and paste in their `requirements.txt` when they search for an artifact. For this we will need `org.carlspring.strongboxdependency.snippet.PypiWheelDependencyFormatter` to be implemented under the `strongbox-storage-pypi-layout-provider` module.

The scope of this task will cover:
* Implementing the `PypiWheelDependencyFormatter`
* Implementing a test class trying different combinations of the PyPi wheel artifact coordinates

One day, when the layout provider is fully implemented, these snippets will be visible in the UI.

You can refer to the following existing implementations for different build tools/layout providers:
* `MavenDependencyFormatter` / `MavenDependencyFormatterTest`
* `NpmDependencyFormatter` / `NpmDependencyFormatterTest`
* `NugetDependencyFormatter` / `NugetDependencyFormatterTest`

Example dependencies defined in a `requirements.txt`:
```
django
bpython==0.12
django-braces==0.2.1
django-model-utils==1.1.0
logutils==0.3.3
South==0.7.6
requests==1.2.0
stripe==1.9.1
dj-database-url==0.2.1
django-oauth2-provider==0.2.4
djangorestframework==2.3.1
```

More examples will be required for other cases as well.

# Related Tasks

This task:
* Is a sub-task of #807.
* Depends on ~~#809~~. 

# Useful Links

* https://pip.pypa.io/en/latest/reference/pip_install/#requirement-specifiers

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by whalenda** [comment]
From PEP 440 (https://www.python.org/dev/peps/pep-0440/#version-ordering-across-different-metadata-versions on Version Identification and Dependency Specification)

"The strict version comparison operator (==) is intended primarily for use when defining dependencies for repeatable deployments of applications while using a shared distribution index."

because this is meant to be used for repeatable deployments == should be the default case

Other possible cases
Version not provided -- throws an error in PypiWheelDependencyFormatter.java

**Comment by carlspring** [comment]
Thanks for you help, @whalenda! :)
