### ISSUE TITLE
Re-create our own implementation of ru.aristar.jnuget.rss.PackageFeed using Spring's AbstractAtomFeedView

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1213]
# Task Description

As a follow up of #611 and in relation to #1131 , we need to replace our code that depends on the `ru.aristar.jnuget.rss.PackageFeed` and implement our own class that uses a `org.springframework.web.servlet.view.feed.AbstractAtomFeedView` based controller instead.

# Task Relationships

This task:
* Is a sub-task of #1215 
* Is a follow-up of: #611
* Is required for: #1130 
* Relates to: #1131 

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by timur27** [comment]
Hi @carlspring. I'll take a look at it if you don't mind. 


Thanks :)

**Comment by carlspring** [comment]
Thanks for offering to help and good luck! :)

**Comment by AlekNiebla** [comment]
I like how this issue sounds, I'll take a look at it

**Comment by carlspring** [comment]
@AlekNiebla , okay -- go for it! @sbespalov will be your point of contact for this, as he's one of our experts.

**Comment by bono007** [comment]
@carlspring I would love to take this one.

**Comment by bono007** [comment]
I am officially heading out on this issue later today. Just putting this here so that its known as tickets can't be assigned to noobs (me) just yet. :)

**Comment by carlspring** [comment]
Thanks, go for it, @bono! :)

**Comment by bono007** [comment]
### Initial analysis of the main usages of PackageFeed:

1. NuGetRepositoryFeatures
	- used by cron to sync the remote NuGet repo w/ the SB one
	- consumes an Atom feed from remote NuGet repo and writes it to SB NuGet repo
1. NuGetArtifactController
	- search endpoints will search the SB NuGet repo and transform the "hits" into an Atom feed which writes to output stream as XML

### Next step
Understand how to replace the above w/ https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/view/feed/AbstractAtomFeedView.html

**Comment by bono007** [comment]
@sbespalov @carlspring 

So Spring leverages [ROME](https://rometools.github.io/rome/) for its RSS and AtomFeed implementations.

Really what AbstractAtomFeedView (via AtomFeedHttpMessageConverter) provides is automatic un/marshalling of the feed using the ROME Feed object model instead of the custom Strongbox PackageFeed and PackageEntry. 

So that makes sense to get off of the hand-rolled solution. However, here is the pain point... ROME only supports basic Feed/Entry schema as well as the [DC Dublin](http://web.resource.org/rss/1.0/modules/dc/) and [Syndication](http://web.resource.org/rss/1.0/modules/syndication/) extensions. However, Strongbox is leveraging the [Microsoft dataservices/metadata](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-odata/617554c6-875d-4a26-b64c-89c449582cbd) extension for the `properties` element in the feed. 

Rome provides the ability to add new "modules" to support extensions. Some extensions are [available](https://rometools.github.io/rome/Modules/index.html) but unfortunately I can't find one for the MS Dataservices/metadata extension.

Here are the [many steps](https://rometools.github.io/rome/RssAndAtOMUtilitiEsROMEV0.5AndAboveTutorialsAndArticles/RssAndAtOMUtilitiEsROMEV0.5TutorialDefiningACustomModuleBeanParserAndGenerator.html) that have to be done to add a new "module". 


### My Thoughts

Is this really worth doing? Is it worth doing right now (priority)? The current implementation of `PackageFeed/PackageEntry/EntryProperties` seems to be working fine. If the above model is replaced w/ the ROME model the controller still has the custom code that loads the Strongbox feed and packages from the NuGet repo. The only difference is that the adaptation of that is now into the ROME object model - not the Strongbox one. Also, it will be a high cost to add the properties module. 

### Options

1. Do nothing
1. Find another ROME module that has some concept or `properties` and use that instead of the MS metadata one.
1. Create a ROME MS metadata module in ROME [modules project](https://rometools.github.io/rome/Modules/index.html) (contribute back) and then use to implement this.
1. Create a ROME MS metadata module locally in Strongbox project and then use to implement this,

**Comment by bono007** [comment]
@carlspring
@sbespalov
@fuss86

Can I get some eyes on my last comment? Thanks

**Comment by steve-todorov** [comment]
Hi @bono007, 

@sbespalov will be able to answer your questions most likely tomorrow :)

**Comment by sbespalov** [comment]
@bono007 thanks for detailed research. As a result it seems there will be no benefits from getting custom ROME module so I suggest to leave this and close the issue.

cc @carlspring

**Comment by carlspring** [comment]
Thank you very much for spending some time to investigate and evaluate this task. It sounds like there is no point to carry on with it for now. I will, therefore, close it.

**Comment by bono007** [comment]
Sounds good. I will focus on 1169.
