### ISSUE TITLE
Investigate Antlr grammar processing issues for the AQL

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1245]
# Task Description

We are getting the following warnings and need to look into the issue and resolve it:
```
[INFO] 
[INFO] --- antlr4-maven-plugin:4.7.1:antlr4 (aql-antlr-java) @ strongbox-aql ---
[INFO] ANTLR 4: Processing source directory /java/opensource/carlspring/strongbox/strongbox-aql/target/antlr4
[INFO] Processing grammar: org/carlspring/strongbox/aql/grammar/AQL.g4
[WARNING] warning(184): org/carlspring/strongbox/aql/grammar/AQL.g4:192:0: One of the token LAYOUT_COORDINATE_NPM_EXTENSION values unreachable. extension is always overlapped by token LAYOUT_COORDINATE_MAVEN_EXTENSION
[WARNING] /java/opensource/carlspring/strongbox/org/carlspring/strongbox/aql/grammar/AQL.g4 [192:0]: One of the token LAYOUT_COORDINATE_NPM_EXTENSION values unreachable. extension is always overlapped by token LAYOUT_COORDINATE_MAVEN_EXTENSION
[WARNING] warning(180): org/carlspring/strongbox/aql/grammar/AQL.g4:357:4: chars '\\' used multiple times in set [\\"\\']
[WARNING] /java/opensource/carlspring/strongbox/org/carlspring/strongbox/aql/grammar/AQL.g4 [357:4]: chars '\\' used multiple times in set [\\"\\']
[WARNING] warning(180): org/carlspring/strongbox/aql/grammar/AQL.g4:357:14: chars '\\' used multiple times in set [\\"\\'\r\n]
[WARNING] /java/opensource/carlspring/strongbox/org/carlspring/strongbox/aql/grammar/AQL.g4 [357:14]: chars '\\' used multiple times in set [\\"\\'\r\n]
[WARNING] warning(180): org/carlspring/strongbox/aql/grammar/AQL.g4:357:28: chars '\\' used multiple times in set [\\"\\']
[WARNING] /java/opensource/carlspring/strongbox/org/carlspring/strongbox/aql/grammar/AQL.g4 [357:28]: chars '\\' used multiple times in set [\\"\\']
```

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by timur27** [comment]
From 8 Warnings here we have two groups of issues actually: 
1. Token LAYOUT_COORDINATE_NPM_EXTENSION unreachable because of LAYOUT_COORDINATE_MAVEN_EXTENSION, which overlaps it. After some research in generated grammar files I found, that both extensions have the same value 'extension' in generated AQL.g4, so I think that is the problem. The question is if we want to change something here, since this warning refers just duplicates in extensions from NPM and maven. Screen attached: 

![extensions-values-screen](https://user-images.githubusercontent.com/22319444/56868598-c46e2400-69f4-11e9-961d-1134128e5e47.png)


2. Warnings 3-8 referred the repeated \\ special character in regex for STRING in lexer rules. Since [ ] brackets assume matching the values repeatedly, I just have removed \\ duplicate. 

Commit here: https://github.com/timur27/strongbox/commit/d8537df4e528221391820fe9901a5a98dd1be357


Please give me your feedback what should I do with first warning. 

Thank you!

**Comment by carlspring** [comment]
@timur27 : Thanks for having a look at this!

@sbespalov : Any thoughts?

**Comment by sbespalov** [comment]
@timur27 can you add a test case in `AqlParserTest` for quoted and unquoted token value to be sure that it works fine after your changes?

**Comment by timur27** [comment]
@sbespalov, thanks for the response! 

I added 2 tests for valid and invalid STRING rule parsing accordingly. I hope I understood you in a right way. You will find the appropriate commit above. 

Thanks for your time!

**Comment by carlspring** [comment]
@timur27 ,

Two things:
* Did you sign the ICLA?
* Have you opened a PR for this?

Thanks! :)
