### ISSUE TITLE
Make the Hazelcast settings configurable

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1392]
# Task Description

Currently, the Hazelcast configuration is hard-coded in the `org.carlspring.strongbox.config.hazelcast.HazelcastConfiguration`. We need to be able to configure this via the `application.yaml` instead.

# Tasks

The following tasks will need to be carried out:
* [ ] Make the Hazelcast settings configurable via the `application.yaml`.
* [ ] ~~Make the Hazelcast settings configurable via the controller.~~ (this is currently not possible)

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by cbrianhill** [comment]
Starting work on this.  I notice that `HazelcastConfiguration.artifactEntryCacheConfig()` appears to be unused.  Should we retain this and hook it up to a cache?  Or should it be cleaned up?

**Comment by sbespalov** [comment]
> Starting work on this. I notice that HazelcastConfiguration.artifactEntryCacheConfig() appears to be unused. Should we retain this and hook it up to a cache? Or should it be cleaned up?

@cbrianhill I think we can drop it

**Comment by cbrianhill** [comment]
@carlspring , @sbespalov and @fuss86 , I have built most of the config file support to host the Hazelcast configurable parameters.  In wiring everything up, I've discovered some Maven dependency issues between modules and I wanted to ask before making any structural changes.  The Hazelcast instantiation lives in `strongbox-data-service`, as Hazelcast is needed in tandem with OrientDB.  But most of the config management infrastructure lives in `strongbox-storage-api` which generally seems like a higher-level package, and has some code that relies on `strongbox-data-service`.  I'm going to think about this overnight, but would appreciate any advice if you have thoughts on how you'd like to approach this.

**Comment by sbespalov** [comment]
@cbrianhill it seems not really clear what is the problem you have with modules. As I see you need to use `@Value` annotation instead of hard-coded values within current Hazelcast configurations.

**Comment by carlspring** [comment]
@cbrianhill : 

I'm afraid I didn't get the problem as well. Would you mind re-phrasing your questions/problem? Thanks! :)

**Comment by cbrianhill** [comment]
Hi,

I've added config attributes in `strongbox.yaml` for Hazelcast, and also added the config attributes in `Configuration` / `MutableConfiguration` and similar classes.  I think what I'm not clear on is how properties defiend in `strongbox.yaml` make it into a PropertySource so that they can be used in `@Value` annotations.  All the `@Value` annotations I can find the code are referring to properties that are not defined in `strongbox.yaml`.

My original approach was to leverage `ConfigurationManagementService` inside `HazelcastConfiguration`, but that was when I ran into dependency issues.

**Comment by sbespalov** [comment]
@cbrianhill thanks for clarification, seems I understand now

@carlspring do you mind if we will put this properties in `application.yaml` instead of `strongbox.yaml`?
we already have logging configuration properties in `application.yaml` and I think the hazelcast caches configuration would be fine to place there as well. This will also resolve the issue that @cbrianhill meet regarding `strongbox.yaml`.

**Comment by carlspring** [comment]
That perfectly fine and it is indeed a better place! Thanks for clarifying!

**Comment by cbrianhill** [comment]
I can certainly do that.  Will we still create configuration UI for these properties?  It seems like all of the properties currently in the configuration UI are persisted in `strongbox.yaml`.

**Comment by sbespalov** [comment]
I am not sure is there a reason to have this properties configurable with UI because applying changes will require application restart.

**Comment by sbespalov** [comment]
BTW, we probably should improve our documentation and provide some clarifications of what properties should be placed within what configuration file.


@carlspring @cbrianhill what do you think?

**Comment by cbrianhill** [comment]
That detail is where I got stuck.  I think it would be technically possible to make `strongbox.yaml` a PropertySource, but it seems as if Hazelcast is needed for OrientDB, and it doesn't look like we have yet implemented a full restart functionality.

I can wire this up to `application.yaml` instead so that the usual Spring Boot config mechanisms will work.  Should we also add it to the config for the wrapper?
