### ISSUE TITLE
Unsolved references when opening the project using IntelliJ

### ISSUE THREAD

**Issue by brendoncheung** [strongbox/strongbox#1986]
Hello all,

First time making an issue,

I am trying to make my first contribution but when I cloned the project into my IntelliJ, I got all sorts of unsolved references, does anybody know how to fix this? thank you!

<img width="1792" alt="Screen Shot 2021-02-08 at 10 03 25 PM" src="https://user-images.githubusercontent.com/18616565/107309987-7c997f00-6a59-11eb-8f1e-6781e046aedb.png">

**Comment by steve-todorov** [comment]
Hi and welcome!

You should check our developer documentation which is located here:
https://strongbox.github.io/developer-guide/index.html

This not an issue with the project, but with your environment. Most likely you haven't configured your `settings.xml` file properly which is why maven / Idea could not resolve the dependencies. I'm closing this issue - if you need help you might want to join our [chat](https://chat.carlspring.org).

Regards,
Steve
