### ISSUE TITLE
Sort out the test issues with the BrowseControllerTest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#529]
The test is currently `@Ignored` due to random failures.

**Comment by carlspring** [comment]
@guidograzioli ,

I've created a follow-up to #444/#454 and #520, could you please investigate why these failures are happening? (If anyone else would like to investigate this issue as well, that's also fine).

Thanks! :)

**Comment by sbespalov** [comment]
Within this task we need properly implementation of `BrowseControllerTest.setup()` method, which is wrong implemented now.
there is a set of methods in `TestCaseWithMavenArtifactGenerationAndIndexing`, which is parent for `BrowseControllerTest`, to create repositories, so we should use these methods in `BrowseControllerTest.setup()`

**Comment by sbespalov** [comment]
Also there should be a `cleanUp` method which removes all that was created in setup
this should be implemented like in other tests that create repositories within startup.

**Comment by sbespalov** [comment]
@sanket407 you still want to take this task?

**Comment by sanket407** [comment]
Yes

On 6 Mar 2018 10:21 am, "Sergey Bespalov" <notifications@github.com> wrote:

@sanket407 <https://github.com/sanket407> you still want to take this task?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/strongbox/strongbox/issues/529#issuecomment-370661824>,
or mute the thread

**Comment by carlspring** [comment]
Fixed by @sanket407 in #647.
