### ISSUE TITLE
Create checkstyle rules for the project based on the coding convention

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#538]
We have a clearly defined [Coding Convention](https://github.com/strongbox/strongbox/wiki/Coding-Convention) in the wiki. It would be great to have rules created for this, so that the convention could be checked by Jenkins when new pull requests have been made.

**Comment by leonorader** [comment]
Your coding convention looks awesome! :) I would like to work on this!
If you accept, could you please decide if I should add it as a plugin, too, or just make a ruleset, so that you can import it into you IDEs?

**Comment by carlspring** [comment]
Hi,

Thanks for the feedback! We'd love the help!

Could you please share the pros and cons of each of these?

**Comment by leonorader** [comment]
Sure! 

Adding as a maven build step:
- PRO: if you have any Checkstyle violation in the code then you will not be able to finish a build, until all of these are corrected (it can go very well if you really followed all the conventions, but it might cause hundreds, even thousands of errors, so it might take a lot of time to fix)
- CON: taking it seriously will allow you to make sure that all the code is consistent and follows all the rules

Using only as a plugin in your IDE:
- PRO: will be able to build even if there are millions of violations
- CON: you might have non-consistent code

So I would suggest to first make the ruleset, then first try to run a check on the code and if it's all okay, then I will add it as a build step. Otherwise fixing those violations can be started. 

:)

**Comment by carlspring** [comment]
Thank you for your explanation!

I believe what you're suggesting is a good idea. Please, feel fre to proceed with the ruleset and we'll see how it works out. :)

**Comment by steve-todorov** [comment]
This has been fixed [PR-889](https://github.com/strongbox/strongbox/pull/889).
