### ISSUE TITLE
`maven-metadata.xml` not updated within group+proxy repository

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#827]
We have a snapshot Maven proxy repository in Strongbox proxying to a Nexus one. The issue is that the information in the `maven-metadata.xml` is not getting updated properly. The snapshot artifact's metadata in Strongbox is [here](https://strongbox.carlspring.org/storages/storage-common-proxies/carlspring/org/carlspring/strongbox/npm-metadata-jackson/1.0-SNAPSHOT/maven-metadata.xml) and the Nexus one is [here](https://dev.carlspring.org/nexus/content/repositories/carlspring/org/carlspring/strongbox/npm-metadata-jackson/1.0-SNAPSHOT/maven-metadata.xml).

The problem is that latest snapshot versions differs:
- In Strongbox, the latest is `1.0-20180917.013403-3`
- In Nexus, the latest is `1.0-20181001.074150-8`

The `maven-metadata.xml` file should be updated at some point with `MavenMetadataManager`, but this is not happening and needs to be fixed.

Steps to reproduce:
* Install Nexus
* Install Strongbox
* Configure Strongbox with a proxy repo to Nexus
* Deploy something to Nexus
* Resolve it from Strongbox
* Deploy a newer version to Nexus
* Resolve the metadata from Strongbox

**Comment by fuss86** [comment]
#858

**Comment by carlspring** [comment]
I think we should implement it like this:
* An artifact gets downloaded
* A request for it comes in:
  * If it's a snapshot
    * If it's a Maven repository:
      * We should have an option for the expiration of metadata (not just the artifacts)
      * Try to get the `maven-metadata.xml.sha1` or `maven-metadata.xml.md5` from the remote. Compare it with the local. If it's newer, get the resource + checksums and return the latest timestamped artfiact when requested

**Comment by sbespalov** [comment]
@carlspring in case of checksum invalidation it's not clear how this will work for group repositories. It will be much overheads if we will check checksum for all proxy repositories in group on every request.

**Comment by carlspring** [comment]
You are right and I've been thinking about this since you raised it the other day. However, I think there are two aspects to consider here:
* The behavior in proxy repositories. If you're proxying a remote repository, then you're definitely working with one copy (umerged) of the remote. So, in this case, (if my theory is true), it would be safe to check the local and remote checksums. Right?
* The behavior in group repositories. In this case you're right. However, how about this -- when we create a merged representation of the `maven-metadata.xml` file, we can keep a record of the checksums of the remote resource. Each time, the file is updated/merged, we'll update the recorded checksum for the respective file that was changed on the remote.

Would this work?

**Comment by sbespalov** [comment]
I think we can invalidate checksums for proxies in group in parallel. So from the performance point of view it will be the same as for direct proxies.
So I think we should try it. :)

**Comment by fuss86** [comment]
@carlspring , @sbespalov please add your comments, please

**Comment by carlspring** [comment]
I believe this covers things quite thoroughly.

There's just one case I'd like to clarify: the case where the group's timeout is different than the proxy's. In this case, whichever's lower should take precedence.

**Comment by sbespalov** [comment]
Regarding **2.2** i thought that it not just first matched but always agregated from group members
